# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djangoGF', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uporabnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uprOpis', models.CharField(max_length=256)),
                ('upr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='komentar',
            name='kmtAvtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoGF.Uporabnik'),
        ),
        migrations.AlterField(
            model_name='novica',
            name='nvcAvtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoGF.Uporabnik'),
        ),
        migrations.AlterField(
            model_name='testiranje',
            name='tstAvtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoGF.Uporabnik'),
        ),
    ]
