/*
    MYSQL
*/

/*--------------------------------TABELA UPORABNIK--------------------------------*/
CREATE TABLE UPORABNIK
(
    ID INT NOT NULL,
    IME VARCHAR(30),
    PRIIMEK VARCHAR(30),
    UP_IME VARCHAR(30) NOT NULL,
    GESLO VARCHAR(256) NOT NULL,
	OPIS TEXT
);

ALTER TABLE UPORABNIK
ADD CONSTRAINT ID PRIMARY KEY (ID);

/*--------------------------------TABELA VLOGA--------------------------------*/
CREATE TABLE VLOGA
(
    ID INT NOT NULL,
    IME VARCHAR(30) NOT NULL,
    UPR_ID INT NOT NULL
);

ALTER TABLE VLOGA
ADD CONSTRAINT ID PRIMARY KEY (ID);

ALTER TABLE VLOGA
ADD CONSTRAINT UPR_FK FOREIGN KEY (UPR_ID)
REFERENCES UPORABNIK (ID);

/*--------------------------------TABELA NOVICA--------------------------------*/
CREATE TABLE NOVICA
(
    ID INT NOT NULL,
    NASLOV VARCHAR(30) NOT NULL,
    DATUM TIMESTAMP NOT NULL,
    SLIKA VARCHAR(256) NOT NULL,
    OPIS VARCHAR(256) NOT NULL,
    BESEDILO TEXT NOT NULL
);

ALTER TABLE NOVICA
ADD CONSTRAINT ID PRIMARY KEY (ID);

/*--------------------------------TABELA TESTIRANJE--------------------------------*/
CREATE TABLE TESTIRANJE
(
    ID INT NOT NULL,
    NASLOV VARCHAR(30) NOT NULL,
    DATUM TIMESTAMP NOT NULL,
    SLIKA VARCHAR(256) NOT NULL,
    OPIS VARCHAR(256) NOT NULL,
    BESEDILO TEXT NOT NULL,
    ZASLON DECIMAL(2,2) NOT NULL,
    FOTOAPARAT INT NOT NULL,
    BATERIJA INT NOT NULL,
    PROSTOR VARCHAR(30) NOT NULL,
    RAM INT NOT NULL,
    OS VARCHAR(30) NOT NULL,
    IZADNO VARCHAR(30)
);

ALTER TABLE TESTIRANJE
ADD CONSTRAINT ID PRIMARY KEY (ID);

/*--------------------------------TABELA KOMENTAR--------------------------------*/
CREATE TABLE KOMENTAR
(
    ID INT NOT NULL,
    BESEDILO VARCHAR(256) NOT NULL,
    NVC_ID INT NOT NULL,
    TST_ID INT NOT NULL,
    UPR_ID INT NOT NULL
);

ALTER TABLE KOMENTAR
ADD CONSTRAINT ID PRIMARY KEY (ID);

ALTER TABLE KOMENTAR
ADD CONSTRAINT NVC_FK FOREIGN KEY (NVC_ID)
REFERENCES NOVICA (ID);

ALTER TABLE KOMENTAR
ADD CONSTRAINT TST_FK FOREIGN KEY (TST_ID)
REFERENCES TESTIRANJE (ID);

ALTER TABLE KOMENTAR
ADD CONSTRAINT UPR_KMT_FK FOREIGN KEY (UPR_ID)
REFERENCES UPORABNIK (ID);
